services:
  sgip-db:
    image: postgres:latest
    container_name: sgip-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgip
    ports:
      - "5432:5432"
    volumes:
      - sgip_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sgip"]
      interval: 5s
      timeout: 5s
      retries: 10

  sgip-webapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sgip-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=sgip-db;Port=5432;Database=sgip;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      sgip-db:
        condition: service_healthy
  
volumes:
  sgip_pgdata: